### ISSUE TITLE
add new emotes

### ISSUE THREAD

**Issue by nikitahaley** [nikitahaley/teledildonics#12]
:getinhere: or :patron: per haraku, :justdoit: and :elo: or :eloknight: per soonkies

**Comment by nikitahaley** [comment]
:tidi: mite b kool 2

**Comment by nikitahaley** [comment]
added patron and tidi in 16a395e

**Comment by adbelle** [comment]
:cleave:

**Comment by nikitahaley** [comment]
http://sendno.de/i/BFztB

**Comment by nikitahaley** [comment]
add :holo: :duarte: :nexus:
