### ISSUE TITLE
Twitch emotes

### ISSUE THREAD

**Issue by nikitahaley** [nikitahaley/teledildonics#26]
Emotes from the following Twitch.tv channels are currently maintained in the pack; as channels have their emote lists updated they will be checked off and signed with the date and commit ID of their last update. An unchecked channel is known to be either missing emotes in the current pack or missing entirely.

- [x] misc ffz/bttv emotes
- [x] ClintStevens
- [x] Forsenlol
- [x] MonotoneTim
- [x] MOONMOON_OW
- [x] raysfire
- [x] Ruwin
- [x] Thatguytagg

To request a new channel or updates to the already included channels, please reply to this issue.

**Comment by ghost** [comment]
raysfire has new emotes due to higher sub-count such as rayst

thatguytagg has new emotes as well due to higher sub-count but not fox related, lower priority

**Comment by ghost** [comment]
ruwin emotes when

**Comment by ghost** [comment]
!lul emotes required http://imgur.com/FtqFRMT

**Comment by nikitahaley** [comment]
Updated 11e7d44 2017-01-19

**Comment by ghost** [comment]
New cheer emotes are out, highest tier of taggCheer is pretty good tbh https://i.imgur.com/PsVSyCY.gif

**Comment by nikitahaley** [comment]
Fixed in dfb38ec
