### ISSUE TITLE
Non-Twitch Emote Requests

### ISSUE THREAD

**Issue by nikitahaley** [nikitahaley/teledildonics#34]
Put all non-Twitch emote requests in replies to this issue
Misc
- [x] :noose:
- [x] :thonking:
- [x] :hmm:

Destiny
- [x] FWC emotes
- [x] Dead Orbit emotes
- [x] New Monarchy emotes
- [x] Other faction emotes (Crucible, Vanguard, Crota's Bane, House of Judgment, Queen's Wrath, Iron Banner)
- [x] :shaxx:
- [x] :cayde: :rook3: should both be the same thing
- [x] Class & subclass emblems
- [x] Subclass super emblems (solar titan ult should additionally call with :balance: and ⚖️)

**Comment by ghost** [comment]
:noose: in some shape or form ex https://i.imgur.com/xIHNp1f.png but smaller

**Comment by ghost** [comment]
Destiny emotes, ex banners (FWC, dead orbit, vanguard), :shaxx:, :balance: can be solar titan, etc.

**Comment by nikitahaley** [comment]
https://puu.sh/v8KQ9/22f515c5c7.png :hmm:

**Comment by ghost** [comment]
https://cdn.discordapp.com/attachments/187255829693464576/299681520627744779/kmh3eck.png emote

**Comment by nikitahaley** [comment]
Emote too large, might consider making a less extreme version to go with :thinkms: tho

**Comment by nikitahaley** [comment]
Added in v1.1.0
