### ISSUE TITLE
Non-Twitch Emote Requests for v1.2.0

### ISSUE THREAD

**Issue by nikitahaley** [nikitahaley/teledildonics#35]
Put all non-Twitch emote requests in replies to this issue. Next update is due around 5/1

Misc
- [x]  👌 
- [x] :gnome:
- [x] :puck: :swide2:

**Comment by nikitahaley** [comment]
👌 tbh fam

**Comment by ghost** [comment]
:gnome: https://i.imgur.com/lwlsEmG.jpg 
:swide2: https://puu.sh/vjGtr/e07fb1bd38.jpg

**Comment by nikitahaley** [comment]
Added in af64eca
