### ISSUE TITLE
Rosie's Emote Suggestions

### ISSUE THREAD

**Issue by ghost** [nikitahaley/teledildonics#40]
On account of Rosie not having a GitHub account and being too lazy to actually make one and do this herself, the following 16 emotes are to be submitted for consideration to be added to the emote pack. 

:awoo:
:azuki2:
:BakAwoo:
:BeatWeiner:
:chocola2:
:cinnamon2:
:cocochan2:
:hanawoo:
:HonkHonk:
:JoshieOC:
:maple2:
:MidnaSmug:
:reimuWink:
:shigure2:
:vanilla2:
:WanWan:

The emotes themselves are of an anime nature, especially 2hu, which may be dangerous considering Kyle's condition.

For some reason I an unable to upload images so here is a link to the emotes: https://drive.google.com/open?id=0B3jsULRmaAo3ZHlKRk9KQmxCMWM

**Comment by nikitahaley** [comment]
fixed in 1393076
